name: Sync Repo to Google Drive

on:
  push:
    branches:
      - Optimization-18082025   # run whenever commits are pushed to main
  schedule:
    - cron: '0 * * * *'   # also run once every hour (UTC)

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup gdrive
        uses: adityak74/gdrive-action@v1
        with:
          service_account_key: ${{ secrets.GDRIVE_KEY }}

      - name: Upload to Google Drive
        run: |
          gdrive files upload --parent ${{ secrets.GDRIVE_FOLDER_ID }} --recursive .

